#!/usr/bin/perl
# eqsl.cc QSL scraping script
# Copyright (c) 2018, molo1134
# 2-clause BSD license

# in order to login, you need to put these two lines in
# $HOME/.eqsllogin:

# login_callsign="YOURCALL"
# login_password="yourpass"

use strict;
use URI::Escape;

my ($login, $pass);

my $start_year = 2000; # a default
my $max_year; # set to current year
(undef,undef,undef,undef,undef,$max_year,undef,undef,undef) = localtime(time);
$max_year += 1900;

my $loginfile = $ENV{'HOME'} . "/.eqsllogin";
my $cookiefile = $ENV{'HOME'} . "/.eqslcookies";

$start_year = $ARGV[0] if defined($ARGV[0]) and $ARGV[0] =~ /^\d{4}$/;
$max_year = $ARGV[1] if defined($ARGV[1]) and $ARGV[1] =~ /^\d{4}$/;

if ($max_year < $start_year) {
  print STDERR "error: starting in $start_year but set to end in $max_year\n";
  exit 1;
}

open(LOGIN, "<", $loginfile) || die "unable to open $loginfile";
while (<LOGIN>) {
  if (/^login_callsign="(.*?)"/) {
    $login = $1;
  }
  if (/^login_password="(.*?)"/) {
    $pass = $1;
  }
}
close(LOGIN);

if (not defined $login or not defined $pass) {
  die "must provide login information.";
}

print "Logging in $login...";

my $url="https://www.eQSL.cc/QSLCard/LoginFinish.cfm";
open (HTTP, '-|', "curl -s -k -L --cookie $cookiefile --cookie-jar $cookiefile --data 'Callsign=${login}&EnteredPassword=${pass}&Login=Go' $url");
while(<HTTP>) {
}
close(HTTP);

#$url = "https://www.eqsl.cc/QSLCard/CookieTest.cfm?sw=1920&sh=1200";
#open (HTTP, '-|', "curl -s -k -L --cookie $cookiefile --cookie-jar $cookiefile $url");
#while(<HTTP>) {
#}
#close(HTTP);

my @cardpages;
my @imgurls;

print "\nretrieving QSLs..\n";

# loop - year, month, archive

for (my $year = $start_year; $year <= $max_year; $year++) {
  for (my $month = 1; $month < 13; $month++) {
    for (my $archive = 0; $archive < 2; $archive++) {
      my $monthtext = $month;
      $monthtext = "0$month" if $month < 10;

      $url = "https://www.eqsl.cc/QSLCard/Inbox.cfm?Archive=$archive&Reject=0&LimitDateMonth=${year}%20$monthtext";
      #print "$url\n";
      open (HTTP, '-|', "curl -s -k -L --cookie $cookiefile --cookie-jar $cookiefile '$url'");
      while(<HTTP>) {
	if (/popupPrintPage\('(DisplayeQSL.cfm\?[^']+)'/) {
	  #print;
	  push (@cardpages, "https://www.eqsl.cc/QSLCard/$1");
	}
      }
      close(HTTP);
      print "\r$year-$monthtext ", scalar @cardpages, " QSLs found";
    }
  }
}
print "\n";

#print join("\n", @cardpages);

my $count = 0;
my @missing;

foreach my $p (@cardpages) {
  #print "$p\n";
  my ($mycall, $hiscall, $date, $band, $mode);
  $mycall = $hiscall = $date = $band = $mode = uri_unescape($p);
  $mycall =~ s/.*VisitorCallsign=([\w\/\\-]+)\&.*/$1/;
  $mycall = uc $mycall;
  $mycall =~ tr/\\\//__/;
  $hiscall =~ s/.*[^r]Callsign=([\w\/\\-]+)\&.*/$1/;
  $hiscall = uc $hiscall;
  $hiscall =~ tr/\\\//__/;
  $date =~ s/.*QSODate=(.*?)\&.*/$1/;
  $date =~ s/\.0//;
  $date =~ s/:00//;
  $date =~ s/[-:]//g;
  $date =~ tr/ /_/;
  $band =~ s/.*Band=(.*?)\&.*/$1/;
  $band = lc $band;
  $mode =~ s/.*Mode=(.*)/$1/;

  my $found = 0;

  open (HTTP, '-|', "curl -s -k -L --cookie $cookiefile --cookie-jar $cookiefile '$p'");
  while(<HTTP>) {
    if (m|<img src="/CFFileServlet/_cf_image/([^"]+)"|) {
      my $file = "$mycall-$date-$hiscall-$band-$mode.png";
      $file =~ tr/\\\//__/;
      my $imgurl = "https://www.eqsl.cc/CFFileServlet/_cf_image/$1";
      #print "$imgurl\n";
      print "$file\n";
      system("curl -s -k -L -o '$file' '$imgurl'");
      $count++;
      $found = 1;
    }
  }
  close(HTTP);
  push (@missing, $p) if $found == 0;
}

print "Expected ", scalar @cardpages, " QSLs.  Found $count images.\n";

print "Pages missing images:\n" if scalar @missing > 0;
print join("\n", @missing);

print "\nDone.\n";

